version: "3.3"
services:
  database:
    build: ./docker/axis2
    ports:
    - "2080:8080"
    volumes:
    - ./com.uber.database/build/lib:/usr/local/tomcat/webapps/axis2/WEB-INF/services
  feedback:
    build: ./docker/axis2
    ports:
    - "3080:8080"
    volumes:
    - ./com.uber.feedback/build/lib:/usr/local/tomcat/webapps/axis2/WEB-INF/services
    environment:
    - DATABASE_SERVICE_URL=http://database:8080/axis2/services/DatabaseService
  invoicing:
    build: ./docker/axis2
    ports:
    - "4080:8080"
    volumes:
    - ./com.uber.invoicing/build/lib:/usr/local/tomcat/webapps/axis2/WEB-INF/services
    environment:
    - DATABASE_SERVICE_URL=http://database:8080/axis2/services/DatabaseService
  navigation:
    build: ./docker/axis2
    ports:
    - "5080:8080"
    volumes:
    - ./com.uber.navigation/build/lib:/usr/local/tomcat/webapps/axis2/WEB-INF/services
  notifier:
    build: ./docker/axis2
    ports:
    - "6080:8080"
    volumes:
    - ./com.uber.notifier/build/lib:/usr/local/tomcat/webapps/axis2/WEB-INF/services
    environment:
    - DATABASE_SERVICE_URL=http://database:8080/axis2/services/DatabaseService
    - NOTIFIER_CALLBACK_URL=http://ode:9763/ode/processes/NotifierCallbackService
  pricing:
    build: ./docker/axis2
    ports:
    - "7080:8080"
    volumes:
      - ./com.uber.pricing/build/lib:/usr/local/tomcat/webapps/axis2/WEB-INF/services
  ode:
    image: opentosca/ode
    ports:
    - "80:9763"
    volumes:
      - ./com.uber.bpel/build/prod:/usr/local/tomcat/webapps/ode/WEB-INF/processes/uber