<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="PricingOrderService"
  targetNamespace="http://order.com/PricingService" xmlns:ps="http://order.com/PricingService"
  xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:types="http://order.com/DataTypes">
  <wsdl:types>
	  <xsd:schema>
	      <xsd:import namespace="http://order.com/DataTypes" schemaLocation="DataTypes.xsd" />             
	  </xsd:schema>
  </wsdl:types>
  
  <wsdl:message name="GetPriceMessage">
    <wsdl:part name="Location" type="xsd:string" />
    <wsdl:part name="CustomerInfo" type="types:Customer" />
  </wsdl:message>
  
  <wsdl:message name="PriceMessage">
    <wsdl:part name="Price" type="xsd:integer" />
  </wsdl:message>
  
  <wsdl:portType name="RequestPricePortType">
    <wsdl:operation name="RequestPrice">
      <wsdl:input message="ps:GetPriceMessage" />
      <wsdl:output message="ps:PriceMessage" />
    </wsdl:operation>
  </wsdl:portType>

  <wsdl:binding name="RequestPriceSOAPBinding" type="ps:RequestPricePortType">
    <!-- leverage off soapbind:binding synchronous style -->
    <soap:binding style="document"
      transport="http://schemas.xmlsoap.org/soap/http" />
    <wsdl:operation name="RequestPrice">
      <!-- again bind to SOAP -->
      <soap:operation
        soapAction="http://supply.com/PurchaseService/wsdl/SendPurchase"
        style="rpc" />
      <!-- further specify that the messages in the wsdl:operation use SOAP -->
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  
  <wsdl:service name="PricingOrderService">
    <wsdl:port name="PricingOrderPort" binding="ps:RequestPriceSOAPBinding">
      <!-- give the binding a network endpoint address or URI of service  -->
      <soap:address location="http://localhost:8080/SOAProject/services/PricingOrderService" />
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
