<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="PricingService"
                  targetNamespace="http://uber.com/PricingService"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:ps="http://uber.com/PricingService">

    <wsdl:import namespace="http://uber.com/PricingService"
                 location="Pricing.wsdl"/>

    <wsdl:service name="PricingService">
        <wsdl:port name="PricingPort"
                   binding="ps:PricingSOAPBinding">
            <soap:address
                    location="http://localhost:9080/com.uber.pricing/services/PricingService"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>
