<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="NotifierCallbackService"
	targetNamespace="http://uber.com/NotifierCallbackService"
	xmlns:ps="http://uber.com/NotifierCallbackService"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:types="http://uber.com/DataTypes"
	xmlns:elements="http://uber.com/Elements">
	
	<wsdl:types>
		<xsd:schema targetNamespace="http://uber.com/Elements">
			<xsd:import namespace="http://uber.com/DataTypes"
				schemaLocation="../../com.uber/wsdl/DataTypes.xsd" />
			<xsd:element name="DriverFoundRequest">
				<xsd:complexType>
					<xsd:all>
						<xsd:element name="Driver" type="types:Driver" />
						<xsd:element name="Customer" type="types:Customer" />
					</xsd:all>
				</xsd:complexType>
			</xsd:element>
		</xsd:schema>
	</wsdl:types>

	<wsdl:message name="DriverFoundRequestMessage">
		<wsdl:part name="parameters"
			element="elements:DriverFoundRequest" />
	</wsdl:message>

	<wsdl:portType name="NotifierCallbackPortType">
		<wsdl:operation name="receiveCallBack">
			<wsdl:input message="ps:DriverFoundRequestMessage" />
		</wsdl:operation>
	</wsdl:portType>

	<wsdl:binding name="NotifierCallbackSOAPBinding"
		type="ps:NotifierCallbackPortType">
		<soap:binding style="document"
			transport="http://schemas.xmlsoap.org/soap/http" />
		<wsdl:operation name="receiveCallBack" >
			<soap:operation style="document" soapAction="http://uber.com/NotifierCallbackService/NotifierCallbackPortType/receiveCallBack" />
			<wsdl:input>
				<soap:body use="literal" />
			</wsdl:input>
		</wsdl:operation>
	</wsdl:binding>

</wsdl:definitions>
